news:
    type:     rest
    prefix:   /news
    resource: "@NewsBundle/Resources/config/routing.yml"

forum:
    type:     rest
    prefix:   /forum
    resource: "@ForumBundle/Resources/config/routing.yml"

app:
    type:     rest
    resource: "@AppBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
