forum:
    type:     rest
    prefix:   /forum
    resource: "@ForumBundle/Resources/config/routing.yml"

app:
    type:     rest
    resource: "@AppBundle/Resources/config/routing.yml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
