forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

user:
    resource: "@UserBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
