forum_category:
    type:     rest
    resource: ForumBundle\Controller\CategoryController

forum_forum:
    type:     rest
    resource: ForumBundle\Controller\ForumController

forum_topic:
    type:     rest
    resource: ForumBundle\Controller\TopicController

forum_post:
    type:     rest
    resource: ForumBundle\Controller\PostController

forum_category_forum:
    type:     rest
    parent:   forum_category
    resource: ForumBundle\Controller\CategoryForumController

forum_forum_topic:
    type:     rest
    parent:   forum_forum
    resource: ForumBundle\Controller\ForumTopicController
